--- 
postsubmits: 
  n-mam/my-kube: 
    - 
      decorate: true
      name: inrepo-postsubmit
      spec: 
        containers: 
          - 
            command: 
              - /bin/printenv
            image: alpine
presubmits: 
  n-mam/my-kube: 
    - 
      always_run: true
      decorate: true
      name: inrepo-presubmit
      skip_report: true
      spec: 
        containers: 
          - 
            command: 
              - /bin/printenv
            image: alpine
