---
apiVersion: v1
kind: Namespace
metadata:
  name: prow

---
apiVersion: v1
kind: Namespace
metadata:
  name: test-pods

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: "deck"
  namespace: prow

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: "horologium"
  namespace: prow

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: "sinker"
  namespace: prow

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "hook"
  namespace: prow

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "tide"
  namespace: prow

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "statusreconciler"
  namespace: prow

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prow-controller-manager
  namespace: prow

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: crier
  namespace: prow

---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: prow
stringData:
  token: 7c8eac9a6af4be95891a31832c1e215052868faf

---
apiVersion: v1
kind: Secret
metadata:
  name: hmac-token
  namespace: prow
stringData:
  hmac: 52680a5de3bdc9c3c80232f672d901f6d6bac977

---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: prow
stringData:
  service-account.json: |
   {
     "region": "ap-south-1",
     "s3_force_path_style": true,
     "access_key": "---insert here----",
     "secret_key": "----insert here----"
   }

---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: test-pods
stringData:
  service-account.json: |
   {
     "region": "ap-south-1",
     "s3_force_path_style": true,
     "access_key": "--insert here---",
     "secret_key": "--insert here---"
   }