apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: s3-credentials
stringData:
  service-account.json: |
   {
     "region": "ap-south-1",
     "s3_force_path_style": true,
     "access_key": "AKIAYRYMEXZVHPI37IHU",
     "secret_key": "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"
   }

